import smtplib
from email.mime.text import MIMEText

PARENT_EMAIL = "elsaaa20102@gmail.com"

SENDER_EMAIL = "elsaaa20102@gmail.com"
SENDER_PASSWORD = "byji jfoh itqe pzcm"


def send_parent_alert(child_name, message, result):

    subject = "🚨 CURA Safety Alert — Potentially Unsafe Interaction"

    body = f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🚨 CURA CHILD SAFETY ALERT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

A potentially unsafe interaction has been detected.

👤 Child Account
-------------------------
Name: {child_name}

⚠️ Risk Assessment
-------------------------
Risk Level : {result['risk_level']}
Risk Score : {result['risk_score']}/100

💬 Flagged Message
-------------------------
"{message}"

🧠 Detection Reasons
-------------------------
{chr(10).join([f"• {reason}" for reason in result['reason']])}

🛡️ Recommended Parent Actions
-------------------------
• Talk calmly with your child
• Review the conversation context
• Avoid panic or confrontation
• Consider blocking/reporting the user
• Continue monitoring future interactions

📌 System Information
-------------------------
Generated by: CURA AI Safety System
Alert Type : Real-Time Behavioral Detection

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This is an automated safety notification.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

    msg = MIMEText(body)

    msg["Subject"] = subject
    msg["From"] = SENDER_EMAIL
    msg["To"] = PARENT_EMAIL

    try:

        server = smtplib.SMTP("smtp.gmail.com", 587)

        server.starttls()

        server.login(SENDER_EMAIL, SENDER_PASSWORD)

        server.sendmail(
            SENDER_EMAIL,
            PARENT_EMAIL,
            msg.as_string()
        )

        server.quit()

        print("✅ Parent alert sent")

    except Exception as e:

        print("❌ Email failed:", e)